services:
  postgres:
    image: postgres:17.2-bookworm
    container_name: '${APP_NAME}_${APP_LOCALE}_postgres'
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    container_name: '${APP_NAME}_${APP_LOCALE}_redis'
    ports:
      - '${REDIS_PORT:-6371}:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
