// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: items.sql

package storage

import (
	"context"
)

const createItem = `-- name: CreateItem :one
insert into items (name)
values ($1)
returning id
`

func (q *Queries) CreateItem(ctx context.Context, db DBTX, name string) (int32, error) {
	row := db.QueryRow(ctx, createItem, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getItem = `-- name: GetItem :one
select id, name
from items
where id = $1
`

func (q *Queries) GetItem(ctx context.Context, db DBTX, id int32) (Item, error) {
	row := db.QueryRow(ctx, getItem, id)
	var i Item
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getItems = `-- name: GetItems :many
select id, name
from items
`

func (q *Queries) GetItems(ctx context.Context, db DBTX) ([]Item, error) {
	rows, err := db.Query(ctx, getItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
