// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package storage

type Item struct {
	ID   int32  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

type User struct {
	ID   int32  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}
